camel:
  springboot:
    name: ScaleGuidedMatch
  
  component:
    servlet:
      mapping:
        # Important: must match any proxy request from API Gateway
        contextPath: /*
        
  dataformat:
    json-jackson:
      object-mapper: jacksonObjectMapper
          
logging:
  level:
    uk.gov.crowncommercial.dts.scale: DEBUG
    org.apache.camel: INFO
    org.springframework: INFO
    org.apache.tomcat: INFO
    org.apache.catalina: INFO
    org.neo4j.ogm: INFO
    
server:
  tomcat:
    accesslog:
      enabled: true
      
spring:
  data:
    neo4j:
      username: neo4j
      password: sbx_graph
      
external:
  lookup-service:    
    url: http://127.0.0.1:8081
    uri-templates:
      find-answers: "/answers?question-instance-uuid={question-instance-uuid}&modifier={modifier}}"
      get-answer: /answers/{answer-uuid}     
      